# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*" # A wildcard that matches all dependencies in the package
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*" # A wildcard that matches all dependencies in the package
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*" # A wildcard that matches all dependencies in the package
