name: debug

on:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-2025
            target: x64
          - runner: windows-11-arm
            target: arm64
          - runner: windows-2022
            target: x64
          - runner: windows-11-arm
            target: arm64
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.target }}
      - run: |
            python3 -c "print('Hello from Windows!')"
            python3 -c "import sys; print(sys.executable); print(sys.version); print(sys.platform)"
